RXR-633 rm unused functionality
InsightRX/PKPDsim pull request #26
Opened 2021-12-20 22:34 UTC by roninsightrx

This removes an earlier implementation of analytic equations, since we now have a newer advan() function that handles that. While sim_core_analytic() is in principle a somewhat more generalized version of advan(), in practice I don’t think there will be a use case for it. I checked that neither sim_core_analytic() nor analytical_eqn_wrapper() is used in any of our other R packages.

2021-12-20 22:39 UTC, karawoo requested changes
I believe we need to update this line:
https://github.com/InsightRX/PKPDsim/blob/3af74cf588c4e256a9e1cac0bb66b483b97fdf0d/R/sim.R#L469

2021-12-21 00:04 UTC, roninsightrx commented
> I believe we need to update this line:
> 
> https://github.com/InsightRX/PKPDsim/blob/3af74cf588c4e256a9e1cac0bb66b483b97fdf0d/R/sim.R#L469

ah darn, then we can't analytical_eqn_wrapper(). Will rollback partially.

2021-12-21 00:07 UTC, karawoo commented
If we're only using it internally maybe let's not export it?

2021-12-21 00:32 UTC, karawoo approved these changes

2021-12-21 00:52 UTC, merged